name: 'Custom GitHub Action'
description: 'A GitHub Action that takes an input and returns the square of the number'
inputs:
  num:
    description: 'Enter a number'
    required: true
    default: "1"
outputs:
  num_squared:
    description: 'Square of the input'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.get-square.outputs.num_squared }}
runs:
  using: "docker"
  image: "Dockerfile"
#runs:
#  using: 'composite'
#  steps:
#    - name: Install Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.10'
#    - name: Install Graphviz
#      uses: tlylt/install-graphviz@v1
#    - name: Install Dependencies
#      run: pip install -r requirements.txt
#      shell: bash
#    - name: Do the thing...
#      id: get-square
#      run: python main.py
#      shell: bash